### ISSUE TITLE
run_spaceInvaders.sh not learning

### ISSUE THREAD

**Issue by glazari** [osh/kerlym#3]
I ran the script run_spaceInvaders.sh for a couple of days and it didn't seem to get any better. 
I ran it on a GPU and it managed to get through 57000 episodes, which I supouse is enought to see some progress. But it seems to still be doing WORSE than the random agent on DeepMind's paper.
Another strange thing is that it seems to never be doing more than 200 frames per episode. (This might explane the poor performance)
I'm wondering why this happend

Here are a couple of lines of the tipical episode I was having
- Episode 00057075 Frame 00000199  Samples: 00100000   Terminal: 00057076  Reward: 30  Epsilon: 0.050000
- Episode 00057076 Frame 00000199  Samples: 00100000   Terminal: 00057077  Reward: 45  Epsilon: 0.050000
- Episode 00057077 Frame 00000199  Samples: 00100000   Terminal: 00057078  Reward: 5   Epsilon: 0.050000
- Episode 00057078 Frame 00000199  Samples: 00100000   Terminal: 00057079  Reward: 10  Epsilon: 0.050000
- Episode 00057079 Frame 00000199  Samples: 00100000   Terminal: 00057080  Reward: 15  Epsilon: 0.050000

**Comment by osh** [comment]
there is a parameter to set the max frames per episode -- 
indeed it is a work in progress, performance against space invaders etc has not yet been validated

**Comment by glazari** [comment]
which parameter is it? in which script can I change it? And how about Pong, has that been validated yet? I'm running it now. (It's running much faster)

**Comment by osh** [comment]
give this a try on the latest branch,
I've done a lot of refactoring!
